### ISSUE TITLE
Semantic conventions for Real User Monitoring

### ISSUE THREAD

**Issue by ivomagi** [open-telemetry/opentelemetry-specification#1679]
**What are you trying to achieve?**

When building a Real User Monitoring solution for browser-based web applications, we have stumbled upon issues where current semantic conventions in OpenTelemetry do not seem to model the client-side too well. The conventions seem to be designed with server-side focus, resulting in some of the concepts not (directly) applicable to the client-side telemetry. 

Looking for interested people to discuss the problems and potential solutions in the field. So if you are working with either Browser or Mobile RUM products and have an interest in any of the following topics, help to plot out a path forward for client-side semantic conventions is appreciated:

- [ ] Issue #1680 - Representing resources
- [ ] Issue #1681 - Representing application as services?
- [ ] Issue #1682 - Representing events with no operation/span mapping
- [ ] Issue #1683 - Representing Websockets

**Comment by svrnm** [comment]
For all of those questions, there might be an (inofficial) answer in the existing implementation with JS / JS-Contrib:

https://www.npmjs.com/package/@opentelemetry/web
and more:
https://www.npmjs.com/package/@opentelemetry/plugin-react-load
https://www.npmjs.com/package/@opentelemetry/instrumentation-document-load
https://www.npmjs.com/package/@opentelemetry/instrumentation-user-interaction

**Comment by ivomagi** [comment]
Unfortunately no. We have studied the opentelemetry-js and opentelemetry-js-contrib repositories while building the RUM product, but exactly on the areas highlighted in this ticket there is no answer in the current SDK nor contrib.

**Comment by ivomagi** [comment]
> For all of those questions, there might be an (inofficial) answer in the existing implementation with JS / JS-Contrib:
> 
> https://www.npmjs.com/package/@opentelemetry/web
> and more:
> https://www.npmjs.com/package/@opentelemetry/plugin-react-load
> https://www.npmjs.com/package/@opentelemetry/instrumentation-document-load
> https://www.npmjs.com/package/@opentelemetry/instrumentation-user-interaction

Unfortunately no. We have studied the opentelemetry-js and opentelemetry-js-contrib repositories while building the RUM product, but exactly on the areas highlighted in this ticket there is no answer in the current SDK nor contrib.

**Comment by pmm-sumo** [comment]
This brings some good topics and I think we could throw few more items with @kkruk-sumo that we've been thinking about. For example:
* a standard way to define the ID of the page - e.g. based on page title or URL
* handling clock inaccuracies (which I believe might be more common in this scenario) - we proposed https://github.com/open-telemetry/opentelemetry-specification/issues/1270 for that purpose
* ability to handle Single-page Applications - e.g. when it's unclear when the page should be considered rendered or so; it might require some extra capabilities to mark it

**Comment by svrnm** [comment]
I took part in the first few minutes of the meeting yesterday but had to leave early, I just heard that you're looking for people who are open to help with this topic. Just wanted to say, that I'd like to participate.

**Comment by martinkuba** [comment]
Hello! I would like to participate as well.
