### ISSUE TITLE
Mark the OpenTracing compatibility section as stable

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#2147]
This issue will serve to track the remaining work to mark the OpenTracing compatibility as stable:

 - [x] Add OpenTracing to the compliance Matrix (#2046)
 - [x] **Only** error mapping should happen in the Shim (#2148)
 - [x] Finalize defining Baggage support (#2137)
 - [x] Decide whether a common `tracer name` should be used when [creating the Shim](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#create-an-opentracing-tracer-shim)
 - [x] Document what happens when a `null` value is passed to ScopeManager.activate() (see https://github.com/open-telemetry/opentelemetry-java/issues/3952)
 - [x] Add a missing **Start Span** section (addressed by #2228)
 - [x] Document version compatibility among different runtime versions (#2218)
 - [x] Document the supported capabilities for OT languages that never implemented `ScopeManager` (#2219)
 - [ ] Support Baggage-only Propagation of `SpanContext` (#2326)
  
The plan has been updated to mark the Spec as stable in _very early_ Q1, and have the first compliant implementations ready by Q1 a well (Python and Java for a start).

@bhs @yurishkuro @tedsuo Please review in case anything else needs to be added.

**Comment by carlosalberto** [comment]
@yurishkuro Please review, as I've update this with a few issues that appeared lately.

**Comment by carlosalberto** [comment]
We have completed all the important tasks, and I'd only wait for #2298 and #2297 as final improvements before we mark this section stable (we could work on the porting guides/documentation after the release).

Opinions @bhs @yurishkuro @tedsuo ?

**Comment by bhs** [comment]
Mega-apologies for the delay on this. I'm fine marking this as stable, particularly given that OT is now officially archived.

**Comment by yurishkuro** [comment]
sgtm

**Comment by jack-berg** [comment]
I've been thinking a bit about this PR to implement [Tracer.close()](https://github.com/open-telemetry/opentelemetry-java/pull/5151) in the java OpenTracing shim. 

The [OpenTracing shim](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#abstract) spec says:

> This functionality will be provided as a bridge layer implementing the [OpenTracing API](https://github.com/opentracing/specification) using the OpenTelemetry API. This layer MUST NOT rely on implementation specific details of any SDK.

Why does the shim operate on the API instead of SDK? Couple reasons it might make sense to instead depend on the SDK:
- There's precedent. The [OpenCensus metrics shim](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opencensus.md#metrics--stats) depends on the metrics SDK, and there's really no way to implement it using just the metrics API, and I would be opposed to extending the metrics API to support it.
- Based on the [opentracing migration guide](https://opentelemetry.io/docs/migration/opentracing/#step-1-install-the-opentelemetry-sdk), it appears that application owners will be the ones using the OpenTracing shim, not instrumentation authors. Application owners don't need to be shielded from the SDK dependency.
- Having the shim depend on the SDK would make implementing the [close](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#close) operation trivial.

**Comment by carlosalberto** [comment]
Hey @jack-berg 

> This layer MUST NOT rely on implementation specific details of any SDK.

I think this is _improper_ wording for the Specification - i.e. we wanted to prevent users from using telemetry-specific functionality in the SDKs, i.e. allow the Shim to specifically configure sampling in the reference Java implementation, or configure `Resource`, for example. In that regard, checking a standard `Closeable` interface wouldn't be considered an offender (will send an amendment to the Spec this week).

So overall there are way more reasons for the OpenCensus to use the SDK, as OpenCensus itself extensively exposes sampling, resources and other _very similar_ implementation details compared to OTel. 

So there are a pair of reasons why I would also prefer to keep it the current way:

1. The OT compatibility section has been declared stable.
2. The `Tracer.Close()` operation is something we added rather late in the OT lifecycle, and hence only two languages implemented it (Java and C++). I don't feel this justifies changing the dependency to the SDK, and we can do a best-effort thing in Java and C++ sides.

cc @yurishkuro

**Comment by yurishkuro** [comment]
@carlosalberto +1 not depending on SDK. But you'd probably still want _some_ language in the spec about Close for the OT languages that supported it. I think for Java it's trivial by checking against an interface, would the same approach be used for C++?

Another alternative is to simply say Close() is not supported by the bridge. I don't recall the reasons why it was allowed in OT, I always felt like it belongs to implementations since someone needs to instantiate them explicitly. And for the auto-instantiation via service registry, the Close could've been a part of _that_ mechanism, not of the Tracer. I am rather interested who would complain about in the first place - do you have any signal of how many people are relying on the shims? My experience with the Go shim was ... mixed.
