### ISSUE TITLE
Is it possible to rename "instrumentation library" to "instrumentation scope" everywhere?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2203]
This initially came from a [discussion](https://github.com/open-telemetry/opentelemetry-specification/pull/1236#issuecomment-970464780) about introducing Logger Name. 

While discussing the issue during the spec SIG meeting we came to a conclusion that the intent for "instrumentation library" was actually to have an "instrumentation scope".

The "instrumentation library" is currently used throughout the spec API and SDK. We want to explore if it is possible to rename "instrumentation library" to "instrumentation scope" without breaking existing stability guarantees.

Note: this should be only done if it is not a breaking change. We must continue honouring our stability guarantees.

Places to check:
- [x] https://github.com/open-telemetry/opentelemetry-java/issues/3961 (*This is a breaking change for Java*).
- [x] https://github.com/open-telemetry/opentelemetry-go/issues/2431 (*This is a breaking change for Go*).
- [x] https://github.com/open-telemetry/opentelemetry-python/issues/2310
- [x] https://github.com/open-telemetry/opentelemetry-dotnet/issues/2725
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/504
- [x] https://github.com/open-telemetry/opentelemetry-cpp/issues/1117
- [x] https://github.com/open-telemetry/opentelemetry-ruby/issues/1052
- [x] https://github.com/open-telemetry/opentelemetry-js/issues/2656 (*This is a breaking change for JS*).
- [x] https://github.com/open-telemetry/opentelemetry-erlang/issues/326
- [x] https://github.com/open-telemetry/opentelemetry-swift/issues/283
- [x] https://github.com/open-telemetry/opentelemetry-rust/issues/675
- [x] https://github.com/open-telemetry/opentelemetry-proto/issues/345
- [x] https://github.com/open-telemetry/opentelemetry-collector/issues/4516

In this spec:
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#instrumentationlibrary
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/overview.md#otlp-support
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#additional-span-interfaces
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#meter-creation

**Comment by dyladan** [comment]
From some of the discussions linked here, its clear that there is still some confusion about what the instrumentation library is, but renaming it to instrumentation scope doesn't clear up that confusion. In my opinion this change is just changing one term for another, more confusing, term. I have a few problems with this. First, it seems that the proposal in the logging discussion actually seeks to not only change the name, but to expand the meaning of the field. The instrumentation library is the library which is performing the instrumentation itself, not the target of the instrumentation. In some cases, the logger name may also be the same, but it may also not be. Second, this may not be breaking in the API surface, but it would definitely be breaking in the export pipeline, requiring exporters and receivers to be changed to use the new name. I don't believe the benefits of changing the name now outweigh the pain of switching the name everywhere.

**Comment by tigrannajaryan** [comment]
>First, it seems that the proposal in the logging discussion actually seeks to not only change the name, but to expand the meaning of the field.

This is not entirely correct. It does not seek to expand the meaning of the field. It seeks to fix the broken description and naming of the field. The initial idea and intent of the field is not correctly reflected neither in the current name of the field nor in its current description. At least this is the takeaway I have from the Spec SIG discussion we had 2 weeks ago.

@bogdandrutu is the person who originally suggested the concept of the "component", later renamed to "instrumentation library". In the spec SIG meeting he suggested that we need to revive the original meaning and fix the name. I think it is worth exploring this idea, but I am not sure we will be able to, it may be too late now. Bogdan, you may want to chime in.

To be clear: I am not strongly advocating for this change myself and can be convinced that we shouldn't do it.

**Comment by tigrannajaryan** [comment]
Update: this would be a breaking change for JS: https://github.com/open-telemetry/opentelemetry-js/issues/2656
Technically this is sufficient to conclude that we cannot make this project-wide change anymore. I don't think we can allow some of the SDKs to use "instrumentation library" and some others "instrumentation scope" as the name of the same concept. That would be confusing and IMO is wrong.

If so, then we are forced to conclude that the renaming is not possible, we have to keep "instrumentation library" as the name of the concept, unless someone else has a suggestion on how we can make it possible.

**Comment by dyladan** [comment]
> @bogdandrutu is the person who originally suggested the concept of the "component", later renamed to "instrumentation library". In the spec SIG meeting he suggested that we need to revive the original meaning and fix the name. I think it is worth exploring this idea, but I am not sure we will be able to, it may be too late now. Bogdan, you may want to chime in.


It was my understanding that `component` referred to the library being instrumented like `mysql`. `InstrumentationLibrary` refers to the library which is doing the instrumenting like `otel-autoinstrumentation-mysql`. In some cases where a library instruments itself (native instrumentations), they may have the same value, but component and `InstrumenatationLibrary` are not the same thing.

**Comment by tigrannajaryan** [comment]
Multiple SDKs reported that this would be a breaking change. We cannot move forward with this.
I am closing this issue as it appears to be a dead end. The change of the name of the "instrumentation library" concept is not possible.
