### ISSUE TITLE
One Logging Bridge per language

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-specification#3824]
### Description

During the joint TC/GC call on Jan 11, we agreed on a few items we'd like to accomplish this year. One such item was creating at least one logging bridge per Language SIG, so that our end-users can start using OTLP Logging natively on their applications.

We'll strive to get at least one logging bridge for each supported language. Language SIGs will be free to decide which bridge to implement based on the needs of their audiences.

### Project Board

To be created.

### Deliverables

For each one of the following languages, there should be at least one logging bridge available, either as part of their core repository or as part of their contrib repository. Usage of such bridge should be documented on opentelemetry.io's website.

Languages (100% of the languages available when this issue was created):

- [ ] One Logging Bridge per language - C++
- [ ] One Logging Bridge per language - .NET
- [ ] One Logging Bridge per language - Erlang
- [ ] One Logging Bridge per language - Go
- [ ] One Logging Bridge per language - Java
- [ ] One Logging Bridge per language - JavaScript
- [ ] One Logging Bridge per language - PHP
- [ ] One Logging Bridge per language - Python
- [ ] One Logging Bridge per language - Ruby
- [ ] One Logging Bridge per language - Rust

### Staffing / Help Wanted

We anticipate that Language SIG maintainers will share the vision that having at least one bridge, hopefully for the most used logging API for the language, is important for the SIG, and therefore, we don't anticipate new staffing requirements. However, we'll try to recruit new contributors to work on this once we have a few examples to follow.

#### Required staffing

@jpkrohling is the sponsor for this project and will work with the individual Language SIGs to implement this.

### Meeting Times

We'll use the regular Language SIGs meetings, as well as the maintainer's meeting on Monday.

### Timeline

We aim to complete this project by the end of 2024.

**Comment by jpkrohling** [comment]
@arminru, could you please assign this to me and add the required labels, so that it appears on the board?

https://github.com/orgs/open-telemetry/projects/29/views/1

**Comment by pellared** [comment]
> We'll strive to get at least one bridge API implementation for each supported SDK.

This is clear.

> Language SIGs will be free to decide which bridge would be the most useful to their audiences.

This is not clear. Is the term [bridge](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#log-appender--bridge) used correctly in this sentence or did you have something else in mind? I am not sure what this sentence is about. I guess it should be "Language SIGs will be free to decide which bridge API implementation would be the most useful to their audiences.". But even then I think the issue description is missing some context. Are there many bridge API implementations?

> For each one of the following SDKs, there should be at least one bridge API available, either as part of their core repository or as part of their contrib repository. Usage of such bridge should be documented on opentelemetry.io's website.

Bridge API != Bridge. Bridge API is supposed to be used to create bridges that the users would then use. I think that we can document two things:

1. Describe how users can use existing bridges
2. Describe how user can create their own bridge using Bridge API

Side note: I am working on Logs for OTel Go. Right now we are on a design stage and I also try to make the specification more clear.

**Comment by pellared** [comment]
I am working on implementing Logs for OTel Go. Right now, we are on a design stage of Bridge API. Here is an issue that can be used for tracking the design phase: https://github.com/open-telemetry/opentelemetry-go/issues/4696

I also try to make the specification more clear in parts that bring confusion.

**Comment by jpkrohling** [comment]
Sorry about the confusion: admittedly, I should have been more thoughtful about the terms used here. By "Bridge API implementation," I simply mean a bridge. Like a slog handler, or a log4j appender, for OTLP.

**Comment by pellared** [comment]
For Go we plan to have an `slog` handler. I just created an issue for tracking: https://github.com/open-telemetry/opentelemetry-go/issues/4829

**Comment by jpkrohling** [comment]
I changed the description a bit to clarify some parts, but I wanted to address some comments here:

>> We'll strive to get at least one logging bridge for each supported SDK
>>
> But... why "at least one" and not simply "one"?

Because we might end up having two :-)

> Are there many bridge API implementations? Do we want the SDK to provide many bridge API implementations?

We want SDKs to offer support for at least one logging API that their users care about. We want Language SIG maintainers to decide which ones to implement.

**Comment by pellared** [comment]
Another note on

> One such item was creating at least one logging bridge per SDK

Log bridge DOES NOT have to be part of SDK (and I think it should not even be if possible).
The idea Bridge API was to have a separation between SDK and bridges so that the bridges can be used by different API implementations (which does not have to be the OTel SDK).

I think it is better to say.

"One such item was creating at least one logging bridge per Language SIG".

**Comment by jpkrohling** [comment]
Agreed, I replaced SDK by language in most occurrences. Thank you for calling that out!

**Comment by srikanthccv** [comment]
Python SIG has one for the stdlib logger [LoggingHandler](https://github.com/open-telemetry/opentelemetry-python/blob/975733c71473cddddd0859c6fcbd2b02405f7e12/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py#L436) already. This is under the experimental flag and being used by several companies to my knowledge. There is also an open issue to support bridge for another popular third-party library https://github.com/open-telemetry/opentelemetry-python/issues/2993 but I guess having a handler for stdlib should be enough?

**Comment by cijothomas** [comment]
OTel .NET provides `ILogger` (the most common logging facade in modern .NET apps), [integration already as a stable feature](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/getting-started-console), used in production by many.
There is support of writing bridges for other logging facades, but this is experimental only.

**Comment by lalitb** [comment]
- OTEL Rust has logging bridge implementation for the [tokio-tracing](https://github.com/tokio-rs/tracing) library which is the most widely used logging framework in the Rust community - https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-appender-tracing

- OTel C++ doesn't have any bridge implementation in the main repo. There are a few contributions for spdlog, glog, log4cxx, and boost.log in progress in the contrib repo. If the ask is to have at least one of these implementations in main repo, we can discuss this internally in next community meeting.

**Comment by jpkrohling** [comment]
Closed in favor of https://github.com/open-telemetry/community/pull/1886

**Comment by jpkrohling** [comment]
Reopening, as we'll use this issue to track at the GC level.

**Comment by trask** [comment]
@jpkrohling same here, move to community repo?
