### ISSUE TITLE
Alignment with OpenTelemetry Collector configuration

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#3963]
I am working on stabilizing the Collector configuration resolution and environment variable support as part of https://github.com/open-telemetry/opentelemetry-collector/milestone/32. 

One of my goals is to bring the File Configuration feature in SDKs and the Collector configuration features to be as similar as possible: it is likely that there will be significant overlap between people writing Collector configurations and people writing SDK configurations.

This is intended to be a meta-issue tracking separate issues that affect Collector and SDK compatibility:
- [x] open-telemetry/opentelemetry-specification#3962
- [x] open-telemetry/opentelemetry-specification#3961
- [x] open-telemetry/opentelemetry-specification#3914
- [x] open-telemetry/opentelemetry-specification#3959

**Comment by tigrannajaryan** [comment]
@mx-psi I assigned this to you since you are already working on it.

**Comment by trask** [comment]
@mx-psi @open-telemetry/configuration-maintainers what do you think of moving this meta issue to https://github.com/open-telemetry/opentelemetry-configuration?

**Comment by jack-berg** [comment]
Yeah i think since this concerns the file config spec, and the not the file config model / schema, it belongs in this repo. Some day, we might consider moving the file config schema to `opentelemetry-configuration` so all related material can be in one repo, similar to what we did moving the OTLP specification to `opentelemetry-proto`.

**Comment by jack-berg** [comment]
All issues are now resolved! Closing.
